server:
  port: 9001
spring:
  fk:
    datasource:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/fk?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  lk:
    datasource:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/lk?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver