server:
  port: 9001

#  type-aliases-package: com.hua.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fk?characterEncoding=UTF-8
    username: root
    password: root

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
